# Generated by Django 4.2.9 on 2024-02-14 12:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('aciklama', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=800)])),
                ('anket_baslik_resmi', models.ImageField(blank=True, default='', null=True, upload_to='anket_baslik_resmi/')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anket',
                'verbose_name_plural': 'Anketler',
                'db_table': 'anket',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Cevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisa_cevap', models.CharField(blank=True, max_length=255, null=True)),
                ('uzun_cevap', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=1000)])),
                ('evet_hayir', models.BooleanField(blank=True, default=True, null=True)),
                ('tarih', models.DateField(blank=True, null=True)),
                ('zaman', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cevap',
                'verbose_name_plural': 'Cevaplar',
                'db_table': 'anket_cevapları',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Çoktan Seçmeli'), ('OPEN_ENDED_SHORT_ANSWER', 'Açık Uçlu-Kısa Cevap'), ('OPEN_ENDED_PARAGRAPH', 'Açık Uçlu-Paragraf'), ('YES_NO', 'Evet/Hayır'), ('DATE', 'Tarih'), ('TIME', 'Zaman')], default='OPEN_ENDED', max_length=40)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('anket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorular', to='anket.anket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'db_table': 'anket_sorulari',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Sonuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('anket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anket.anket')),
                ('cevap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anket.cevap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sonuc',
                'verbose_name_plural': 'Sonuclar',
                'db_table': 'anket_sonucu',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Secenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secenekler', to='anket.soru')),
            ],
            options={
                'verbose_name': 'Secenek',
                'verbose_name_plural': 'Secenekler',
                'db_table': 'secenekler',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='cevap',
            name='secenek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anket.secenek'),
        ),
        migrations.AddField(
            model_name='cevap',
            name='soru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anket.soru'),
        ),
        migrations.AddField(
            model_name='cevap',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
