# Generated by Django 5.0.2 on 2024-02-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anket',
            old_name='baslik',
            new_name='anket_baslik',
        ),
    ]
