# Generated by Django 4.2.9 on 2024-02-11 09:50

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import meta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.CharField(blank=True, max_length=255, null=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('haber_baslik_resmi', models.ImageField(blank=True, default='', null=True, upload_to='haber_baslik_resmi/')),
                ('link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('pub_date', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=100)),
                ('post_views_count', models.CharField(blank=True, max_length=255, null=True)),
                ('copyrightYear', models.DateField(auto_now=True, null=True)),
                ('metadesc', models.TextField(blank=True, null=True)),
                ('focuskeywords', models.CharField(blank=True, max_length=255, null=True)),
                ('keywordsynonyms', models.CharField(blank=True, max_length=255, null=True)),
                ('_thumbnail_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='category.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'post',
                'ordering': ['-pk'],
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
