# Generated by Django 4.2.9 on 2024-02-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_haber_baslik_resmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='haber_baslik_resmi',
            field=models.ImageField(blank=True, default='/haber_baslik_resmi/turkiye-ve-dunyadaki-en-populer-girisimcilik-zirveleri-StartupTeknoloji-1.jpg', max_length=255, null=True, upload_to='haber_baslik_resmi/'),
        ),
    ]
