# Generated by Django 4.2.9 on 2024-02-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_haber_baslik_resmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
