# Generated by Django 4.2.9 on 2024-02-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='haber_baslik_resmi',
            field=models.ImageField(blank=True, default='/haber_baslik_resmi/startupteknoloji-default.png', max_length=255, null=True, upload_to='haber_baslik_resmi/'),
        ),
    ]
