# Generated by Django 4.2.9 on 2024-02-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_alter_post_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
