# Generated by Django 4.2.9 on 2024-02-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_remove_post_pub_date_alter_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
