# Generated by Django 4.2.9 on 2024-02-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
