# Generated by Django 4.2.9 on 2024-02-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_user_author_yazarin_instagram_adresi_linki_and_more'),
        ('post', '0023_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author'),
        ),
    ]
