# Generated by Django 4.2.9 on 2024-02-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
