# Generated by Django 4.2.9 on 2024-02-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_user'),
        ('post', '0027_post_author_foreign_key_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_foreign_key',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author'),
        ),
    ]
