# Generated by Django 4.2.9 on 2024-02-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0032_alter_post_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='publish_status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=100),
        ),
    ]
