# Generated by Django 4.2.9 on 2024-02-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_alter_post_post_date_alter_post_publish_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_status',
        ),
        migrations.AddField(
            model_name='post',
            name='yayimlanma_durumu',
            field=models.CharField(choices=[('Taslak', 'Taslak'), ('Yayinda', 'Yayinda')], default='Yayinda', max_length=10),
        ),
    ]
