# Generated by Django 4.2.9 on 2024-02-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_rename_category_industrycategory_category_name'),
        ('girisim', '0003_remove_girisim_girisimin_bulundugu_altsektor'),
    ]

    operations = [
        migrations.AddField(
            model_name='girisim',
            name='girisimin_bulundugu_altsektor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investor.industrysubcategory'),
        ),
    ]
