# Generated by Django 4.2.9 on 2024-02-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girisim', '0004_girisim_girisimin_bulundugu_altsektor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girisim',
            old_name='sirketin_websitesi',
            new_name='sirketin_websitesi_varsa',
        ),
        migrations.RemoveField(
            model_name='girisim',
            name='sirketin_sosyal_medya_hesabi',
        ),
    ]
