# Generated by Django 4.2.9 on 2024-02-14 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girisim', '0005_rename_sirketin_websitesi_girisim_sirketin_websitesi_varsa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girisim',
            name='ekip_arkadasi_telefonu',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='girisim',
            name='girisim_ozeti',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=1000)]),
        ),
    ]
