# Generated by Django 4.2.9 on 2024-02-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girisim', '0007_rename_girisim_ile_ilgili_dokumanlar_girisim_girisim_ile_ilgili_dokumanlarin_linki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girisim',
            name='girisim_adi',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
