# Generated by Django 4.2.9 on 2024-02-11 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Industry Category',
                'verbose_name_plural': 'Industry Categories',
                'db_table': 'industry_category',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='IndustrySubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Industry Subcategory',
                'verbose_name_plural': 'Industry Subcategories',
                'db_table': 'industry_subcategory',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('company_logo', models.ImageField(blank=True, default='', null=True, upload_to='company_logo/')),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_slogan', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('company_foundation_date', models.DateField(blank=True, null=True)),
                ('company_social_media', models.URLField(blank=True, null=True)),
                ('employee_number', models.PositiveIntegerField(blank=True, null=True)),
                ('company_location_city', models.PositiveSmallIntegerField(choices=[(1, 'ADANA'), (2, 'ADIYAMAN'), (3, 'AFYONKARAHİSAR'), (4, 'AGRI'), (5, 'AMASYA'), (6, 'ANKARA'), (7, 'ANTALYA'), (8, 'ARTVIN'), (9, 'AYDIN'), (10, 'BALIKESIR'), (11, 'BILECIK'), (12, 'BINGOL'), (13, 'BITLIS'), (14, 'BOLU'), (15, 'BURDUR'), (16, 'BURSA'), (17, 'CANAKKALE'), (18, 'CANKIRI'), (19, 'CORUM'), (20, 'DENIZLI'), (21, 'DIYARBAKIR'), (22, 'EDIRNE'), (23, 'ELAZIG'), (24, 'ERZINCAN'), (25, 'ERZURUM'), (26, 'ESKISEHIR'), (27, 'GAZIANTEP'), (28, 'GİRESUN'), (29, 'GUMUSHANE'), (30, 'HAKKARI'), (31, 'HATAY'), (32, 'ISPARTA'), (33, 'MERSIN'), (34, 'ISTANBUL'), (35, 'IZMIR'), (36, 'KARS'), (37, 'KASTAMONU'), (38, 'KAYSERI'), (39, 'KIRKLARELI'), (40, 'KIRSEHIR'), (41, 'KOCAELI'), (42, 'KONYA'), (43, 'KUTAHYA'), (44, 'MALATYA'), (45, 'MANISA'), (46, 'KAHRAMANMARAS'), (47, 'MARDIN'), (48, 'MUGLA'), (49, 'MUS'), (50, 'NEVSEHIR'), (51, 'NIGDE'), (52, 'ORDU'), (53, 'RIZE'), (54, 'SAKARYA'), (55, 'SAMSUN'), (56, 'SIIRT'), (57, 'SINOP'), (58, 'SIVAS'), (59, 'TEKIRDAG'), (60, 'TOKAT'), (61, 'TRABZON'), (62, 'TUNCELI'), (63, 'SANLIURFA'), (64, 'USAK'), (65, 'VAN'), (66, 'YOZGAT'), (67, 'ZONGULDAK'), (68, 'AKSARAY'), (69, 'BAYBURT'), (70, 'KARAMAN'), (71, 'KIRIKKALE'), (72, 'BATMAN'), (73, 'SIRNAK'), (74, 'BARTIN'), (75, 'ARDAHAN'), (76, 'IGDIR'), (77, 'YALOVA'), (78, 'KARABUK'), (79, 'KILIS'), (80, 'OSMANIYE'), (81, 'DUZCE')], default=34)),
                ('investment_done', models.BooleanField(blank=True, default=False, null=True)),
                ('investment_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('finance_used', models.BooleanField(blank=True, default=False, null=True)),
                ('companization_done', models.BooleanField(blank=True, default=False, null=True)),
                ('invoicing', models.BooleanField(blank=True, default=False, null=True)),
                ('calisma_durumu', models.BooleanField(blank=True, default=False, null=True)),
                ('company_purchasing_merging', models.BooleanField(blank=True, default=False, null=True)),
                ('public_offering', models.BooleanField(blank=True, default=False, null=True)),
                ('company_mentoring', models.PositiveSmallIntegerField(choices=[(1, 'B2B'), (2, 'B2C'), (3, 'Basın')], default=3)),
                ('ekip_arkadasi_adi', models.CharField(blank=True, max_length=40, null=True)),
                ('ekip_arkadasi_soyadi', models.CharField(blank=True, max_length=40, null=True)),
                ('ekip_arkadasi_email', models.CharField(blank=True, max_length=40, null=True)),
                ('ekip_arkadasi_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('ekip_arkadasi_linkedin', models.URLField(blank=True, null=True)),
                ('ekip_arkadasi_department', models.PositiveSmallIntegerField(choices=[(1, 'ADANA'), (2, 'ADIYAMAN'), (3, 'AFYONKARAHİSAR'), (4, 'AGRI'), (5, 'AMASYA'), (6, 'ANKARA'), (7, 'ANTALYA'), (8, 'ARTVIN'), (9, 'AYDIN'), (10, 'BALIKESIR'), (11, 'BILECIK'), (12, 'BINGOL'), (13, 'BITLIS'), (14, 'BOLU'), (15, 'BURDUR'), (16, 'BURSA'), (17, 'CANAKKALE'), (18, 'CANKIRI'), (19, 'CORUM'), (20, 'DENIZLI'), (21, 'DIYARBAKIR'), (22, 'EDIRNE'), (23, 'ELAZIG'), (24, 'ERZINCAN'), (25, 'ERZURUM'), (26, 'ESKISEHIR'), (27, 'GAZIANTEP'), (28, 'GİRESUN'), (29, 'GUMUSHANE'), (30, 'HAKKARI'), (31, 'HATAY'), (32, 'ISPARTA'), (33, 'MERSIN'), (34, 'ISTANBUL'), (35, 'IZMIR'), (36, 'KARS'), (37, 'KASTAMONU'), (38, 'KAYSERI'), (39, 'KIRKLARELI'), (40, 'KIRSEHIR'), (41, 'KOCAELI'), (42, 'KONYA'), (43, 'KUTAHYA'), (44, 'MALATYA'), (45, 'MANISA'), (46, 'KAHRAMANMARAS'), (47, 'MARDIN'), (48, 'MUGLA'), (49, 'MUS'), (50, 'NEVSEHIR'), (51, 'NIGDE'), (52, 'ORDU'), (53, 'RIZE'), (54, 'SAKARYA'), (55, 'SAMSUN'), (56, 'SIIRT'), (57, 'SINOP'), (58, 'SIVAS'), (59, 'TEKIRDAG'), (60, 'TOKAT'), (61, 'TRABZON'), (62, 'TUNCELI'), (63, 'SANLIURFA'), (64, 'USAK'), (65, 'VAN'), (66, 'YOZGAT'), (67, 'ZONGULDAK'), (68, 'AKSARAY'), (69, 'BAYBURT'), (70, 'KARAMAN'), (71, 'KIRIKKALE'), (72, 'BATMAN'), (73, 'SIRNAK'), (74, 'BARTIN'), (75, 'ARDAHAN'), (76, 'IGDIR'), (77, 'YALOVA'), (78, 'KARABUK'), (79, 'KILIS'), (80, 'OSMANIYE'), (81, 'DUZCE')], default=34)),
                ('ekip_arkadasi_position', models.PositiveSmallIntegerField(choices=[(1, 'ADANA'), (2, 'ADIYAMAN'), (3, 'AFYONKARAHİSAR'), (4, 'AGRI'), (5, 'AMASYA'), (6, 'ANKARA'), (7, 'ANTALYA'), (8, 'ARTVIN'), (9, 'AYDIN'), (10, 'BALIKESIR'), (11, 'BILECIK'), (12, 'BINGOL'), (13, 'BITLIS'), (14, 'BOLU'), (15, 'BURDUR'), (16, 'BURSA'), (17, 'CANAKKALE'), (18, 'CANKIRI'), (19, 'CORUM'), (20, 'DENIZLI'), (21, 'DIYARBAKIR'), (22, 'EDIRNE'), (23, 'ELAZIG'), (24, 'ERZINCAN'), (25, 'ERZURUM'), (26, 'ESKISEHIR'), (27, 'GAZIANTEP'), (28, 'GİRESUN'), (29, 'GUMUSHANE'), (30, 'HAKKARI'), (31, 'HATAY'), (32, 'ISPARTA'), (33, 'MERSIN'), (34, 'ISTANBUL'), (35, 'IZMIR'), (36, 'KARS'), (37, 'KASTAMONU'), (38, 'KAYSERI'), (39, 'KIRKLARELI'), (40, 'KIRSEHIR'), (41, 'KOCAELI'), (42, 'KONYA'), (43, 'KUTAHYA'), (44, 'MALATYA'), (45, 'MANISA'), (46, 'KAHRAMANMARAS'), (47, 'MARDIN'), (48, 'MUGLA'), (49, 'MUS'), (50, 'NEVSEHIR'), (51, 'NIGDE'), (52, 'ORDU'), (53, 'RIZE'), (54, 'SAKARYA'), (55, 'SAMSUN'), (56, 'SIIRT'), (57, 'SINOP'), (58, 'SIVAS'), (59, 'TEKIRDAG'), (60, 'TOKAT'), (61, 'TRABZON'), (62, 'TUNCELI'), (63, 'SANLIURFA'), (64, 'USAK'), (65, 'VAN'), (66, 'YOZGAT'), (67, 'ZONGULDAK'), (68, 'AKSARAY'), (69, 'BAYBURT'), (70, 'KARAMAN'), (71, 'KIRIKKALE'), (72, 'BATMAN'), (73, 'SIRNAK'), (74, 'BARTIN'), (75, 'ARDAHAN'), (76, 'IGDIR'), (77, 'YALOVA'), (78, 'KARABUK'), (79, 'KILIS'), (80, 'OSMANIYE'), (81, 'DUZCE')], default=34)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company_industry_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investor.industrycategory')),
                ('company_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investor.industrysubcategory')),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
                'db_table': 'investor',
                'ordering': ['-pk'],
            },
        ),
    ]
