# Generated by Django 4.2.9 on 2024-02-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_remove_industrysubcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrysubcategory',
            name='category_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investor.industrycategory'),
            preserve_default=False,
        ),
    ]
