# Generated by Django 5.0.2 on 2024-02-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='advertisement_alt_resmi',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='advertisement_alt_resmi_views',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='reklam_gosterim_yeri',
            field=models.CharField(default='Üst', max_length=15),
        ),
    ]
