# Generated by Django 5.0.2 on 2024-02-27 16:29

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_remove_advertisement_advertisement_alt_resmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='advertisement_alt_resmi',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='anasayfa_alt_taraf_reklam_resmi/'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advertisement_alt_resmi_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='reklam_gosterim_yeri',
            field=models.CharField(choices=[('Üst', 'Üst'), ('Alt', 'Alt'), ('Her İkiside', 'Her İkiside')], default='Her İkiside', max_length=15),
        ),
    ]
