# Generated by Django 5.0.2 on 2024-02-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisement_advertisement_alt_resmi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='advertisement_alt_resmi',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='advertisement_alt_resmi_views',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='reklam_gosterim_yeri',
            field=models.CharField(choices=[('Üst', 'Üst'), ('Alt', 'Alt'), ('Her İkiside', 'Her İkiside')], default='Üst', max_length=15),
        ),
    ]
