# Generated by Django 4.2.9 on 2024-02-11 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Girisimci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(default='', upload_to='profile_pictures/')),
                ('linkedin_profiliniz', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=1000)])),
                ('slug', models.SlugField(blank=True, max_length=254, null=True)),
                ('sirket_adi', models.CharField(max_length=254, unique=True)),
                ('dogum_gununuz', models.DateField(blank=True, null=True)),
                ('egitim_seviyesi', models.CharField(blank=True, choices=[('İlkokul', 'İlkokul'), ('Ortaokul', 'Ortaokul'), ('Lise', 'Lise'), ('Lisans', 'Lisans'), ('Yüksek Lisans', 'Yüksek Lisans'), ('Doktora', 'Doktora')], max_length=15, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Girişimci',
                'verbose_name_plural': 'Girişimciler',
                'db_table': 'girisimci',
                'ordering': ['-pk'],
            },
        ),
    ]
