# Generated by Django 4.2.9 on 2024-02-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='yazarin_twitter_x_adresi_linki',
            field=models.URLField(blank=True, null=True),
        ),
    ]
