# Generated by Django 4.2.9 on 2024-02-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user_profile_pictures/'),
        ),
    ]
