# Generated by Django 5.0.2 on 2024-02-27 15:15

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterReklami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kampanya_creator_adi', models.CharField(max_length=255)),
                ('kampanya_creator_soyadi', models.CharField(max_length=255)),
                ('kampanya_basligi', models.CharField(max_length=255, unique=True)),
                ('sirket_adi', models.CharField(max_length=255)),
                ('kampanya_baslangic_tarihi', models.DateField()),
                ('kampanyanin_websitesinin_linki', models.URLField()),
                ('advertisement_alt_resmi', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='anasayfa_alt_taraf_reklam_resmi/')),
                ('advertisement_alt_resmi_views', models.PositiveIntegerField(default=0)),
                ('reklam_gosterim_yeri', models.CharField(default='Alt', max_length=15)),
                ('max_views_per_image', models.PositiveIntegerField(blank=True, default=100, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('kampanya_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alt_Reklam',
                'verbose_name_plural': 'Alt_Reklamlar',
                'db_table': 'footer_reklami',
                'ordering': ['-pk'],
            },
        ),
    ]
