# Generated by Django 4.2.9 on 2024-02-20 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='yorum_birakanin_eposta_adresi',
            field=models.EmailField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='yorum_birakanin_ismi',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=500)]),
        ),
    ]
