# Generated by Django 4.2.9 on 2024-02-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='yorum_birakanin_ismi',
            field=models.CharField(max_length=80),
        ),
    ]
